/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.*;
import java.util.*;

/**
 *
 * @author Fabián
 */
public class Alquiler_Vehiculo extends javax.swing.JFrame {

    /**
     * Creates new form SolicituddeAlquiler
     */
    public Alquiler_Vehiculo() {
        initComponents();
    }
    public Generar_Alquiler Alquiler;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        COMBOMODEL = new javax.swing.JComboBox<>();
        TXTEXTRA = new javax.swing.JTextArea();
        COMBOPASSAGER = new javax.swing.JComboBox<>();
        COMBOBRANCH = new javax.swing.JComboBox<>();
        COMBOYEAR = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        FILTRAR = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Solicitud alquiler de vehículo");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Pasajeros:");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Marca:");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Modelo:");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Año:");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Extras que desea:");

        COMBOMODEL.setBackground(new java.awt.Color(255, 255, 255));
        COMBOMODEL.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        COMBOMODEL.setForeground(new java.awt.Color(0, 0, 0));
        COMBOMODEL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automóvil", "Pick up", "SUV", "4x4 Off-Road" }));
        COMBOMODEL.setBorder(new javax.swing.border.MatteBorder(null));
        COMBOMODEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBOMODELActionPerformed(evt);
            }
        });

        TXTEXTRA.setBackground(new java.awt.Color(255, 255, 255));
        TXTEXTRA.setColumns(20);
        TXTEXTRA.setForeground(new java.awt.Color(0, 0, 0));
        TXTEXTRA.setRows(5);

        COMBOPASSAGER.setBackground(new java.awt.Color(255, 255, 255));
        COMBOPASSAGER.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        COMBOPASSAGER.setForeground(new java.awt.Color(0, 0, 0));
        COMBOPASSAGER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "7", "8" }));
        COMBOPASSAGER.setBorder(new javax.swing.border.MatteBorder(null));

        COMBOBRANCH.setBackground(new java.awt.Color(255, 255, 255));
        COMBOBRANCH.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        COMBOBRANCH.setForeground(new java.awt.Color(0, 0, 0));
        COMBOBRANCH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Nissan", "Honda", "Ford", "Hyndai", "Mitsubishi", "BMW", "Mazda" }));
        COMBOBRANCH.setBorder(new javax.swing.border.MatteBorder(null));
        COMBOBRANCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBOBRANCHActionPerformed(evt);
            }
        });

        COMBOYEAR.setBackground(new java.awt.Color(255, 255, 255));
        COMBOYEAR.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        COMBOYEAR.setForeground(new java.awt.Color(0, 0, 0));
        COMBOYEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", " " }));
        COMBOYEAR.setBorder(new javax.swing.border.MatteBorder(null));
        COMBOYEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBOYEARActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Filtros para el vehículo");

        FILTRAR.setText("Filtrar");
        FILTRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FILTRARMouseClicked(evt);
            }
        });
        FILTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FILTRARActionPerformed(evt);
            }
        });

        EXIT.setText("Atrás");
        EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITMouseClicked(evt);
            }
        });
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(EXIT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FILTRAR)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(1, 1, 1)
                                .addComponent(COMBOBRANCH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(2, 2, 2)
                                .addComponent(COMBOMODEL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(1, 1, 1)
                                .addComponent(COMBOYEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(COMBOPASSAGER, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(4, 4, 4)
                                .addComponent(TXTEXTRA, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(COMBOPASSAGER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(COMBOBRANCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(COMBOMODEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(COMBOYEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTEXTRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FILTRAR)
                    .addComponent(EXIT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COMBOMODELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOMODELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOMODELActionPerformed

    private void COMBOBRANCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOBRANCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOBRANCHActionPerformed

    private void FILTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FILTRARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FILTRARActionPerformed

    private void COMBOYEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOYEARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOYEARActionPerformed

    private void FILTRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FILTRARMouseClicked
        String marca = COMBOBRANCH.getSelectedItem().toString();
        String modelo = COMBOMODEL.getSelectedItem().toString();
        int año=Integer.parseInt(COMBOYEAR.getSelectedItem().toString());
        int pasajeros = Integer.parseInt(COMBOPASSAGER.getSelectedItem().toString());
        
        ArrayList<Nodo_Vehiculo> lista = new ArrayList();
        lista=General.Vehiculos_Registrados.filtrar(modelo, marca, año, pasajeros, General.Vehiculos_Registrados.getHead(), lista);
        if(!lista.isEmpty()){
            String datos="RESULTADOS\n";
            for (Nodo_Vehiculo lista1 : lista) {
                Vehiculo carro=lista1.getCarro();
                datos+="\nPlaca: [" + carro.getPlaca() +"]\n"
                        + "Modelo: [" + carro.getModelo() + "]\n"
                        +"Marca: [" + carro.getMarca() + "]\n"
                        +"Año: ["+carro.getAño()+"]\n"
                        +"Capacidad: [" + carro.getCapacidad() + "]\n"
                        +"----------------------------------------------------------";
            }
            Alquiler1 ventana = new Alquiler1();
            ventana.setVisible(true);
            ventana.Alquiler = Alquiler;
            ventana.setLista(lista,datos);
            this.setVisible(false);
            
            
        }
        else{
           
        }
            
        
    }//GEN-LAST:event_FILTRARMouseClicked

    private void EXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITMouseClicked
        Generar_Alquiler ventana = new Generar_Alquiler();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EXITMouseClicked

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alquiler_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alquiler_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alquiler_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alquiler_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alquiler_Vehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> COMBOBRANCH;
    private javax.swing.JComboBox<String> COMBOMODEL;
    private javax.swing.JComboBox<String> COMBOPASSAGER;
    private javax.swing.JComboBox<String> COMBOYEAR;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton FILTRAR;
    private javax.swing.JTextArea TXTEXTRA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
