
package Interfaz;
import java.util.*;
import Clases.*;

public class Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarAlquiler
     */
    public Estadisticas() {
        initComponents();
    }
    public static ArrayList<Double> Montos;
    public static ArrayList<Double> Promedios;
    public static ArrayList<String>Categorias;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NUMBERS = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TOPCLIENTS = new javax.swing.JRadioButton();
        TOPCARS = new javax.swing.JRadioButton();
        MONEY = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RESULT = new javax.swing.JTextArea();
        EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        NUMBERS.add(TOPCLIENTS);
        TOPCLIENTS.setText("Top 5 Clientes");
        TOPCLIENTS.setActionCommand("Top 5 Clientes");
        TOPCLIENTS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TOPCLIENTSStateChanged(evt);
            }
        });

        NUMBERS.add(TOPCARS);
        TOPCARS.setText("Top 5 Vehiculos");
        TOPCARS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TOPCARSStateChanged(evt);
            }
        });

        NUMBERS.add(MONEY);
        MONEY.setText("Montos & Promedios");
        MONEY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MONEYStateChanged(evt);
            }
        });

        RESULT.setColumns(20);
        RESULT.setRows(5);
        jScrollPane1.setViewportView(RESULT);

        EXIT.setText("Atrás");
        EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITMouseClicked(evt);
            }
        });
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EXIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MONEY)
                            .addComponent(TOPCARS)
                            .addComponent(TOPCLIENTS))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(TOPCLIENTS)
                .addGap(18, 18, 18)
                .addComponent(TOPCARS)
                .addGap(18, 18, 18)
                .addComponent(MONEY)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITMouseClicked
        MenuPrincipal menu = new MenuPrincipal();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_EXITMouseClicked

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    private void MONEYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MONEYStateChanged
        if (MONEY.isSelected()){
           General.Alquileres_Registrados.montopromedio();
           String datos="";
           int index=0;
          for(String item:Categorias){
              datos+="\n"+item+"\n"
                      +"Monto Total= "+Montos.get(index)+"\n"
                      +"Promedio= "+Promedios.get(index)+"\n";
              index+=1;
          }
          RESULT.setText(datos);
       }
    }//GEN-LAST:event_MONEYStateChanged

    private void TOPCLIENTSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TOPCLIENTSStateChanged
       if (TOPCLIENTS.isSelected()){
            ArrayList<Nodo_Cliente> top5;
            String datos="";
            int num=1;
           top5=General.Clientes_Registrados.top5();
           for(Nodo_Cliente item:top5){
               datos+="Num " + num + "\n"+General.Clientes_Registrados.printPersona(item.getPersona());
               num+=1;
           }
           RESULT.setText(datos);
       }
    }//GEN-LAST:event_TOPCLIENTSStateChanged

    private void TOPCARSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TOPCARSStateChanged
        if (TOPCARS.isSelected()){
            ArrayList<Nodo_Vehiculo> top5;
            String datos="";
            int num=1;
           top5=General.Vehiculos_Registrados.Top5();
           for(Nodo_Vehiculo item:top5){
               datos+="Num " + num +"\n"+ General.Vehiculos_Registrados.buscar(item.getCarro().getPlaca());
               num+=1;
           }
           RESULT.setText(datos);
       }
    }//GEN-LAST:event_TOPCARSStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JRadioButton MONEY;
    private javax.swing.ButtonGroup NUMBERS;
    private javax.swing.JTextArea RESULT;
    private javax.swing.JRadioButton TOPCARS;
    private javax.swing.JRadioButton TOPCLIENTS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
