package Interfaz;

import Clases.*;

public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarVehiculo
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CLIENTES = new javax.swing.JButton();
        VEHICULOS = new javax.swing.JButton();
        ALQUILERES = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DEVOLUTION = new javax.swing.JButton();
        ATTEND = new javax.swing.JButton();
        NUMBERS = new javax.swing.JButton();

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Menú");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(170, 0, 80, 30);

        jButton1.setText("SALIR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(291, 410, 90, 20);

        CLIENTES.setText("Clientes");
        CLIENTES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLIENTESMouseClicked(evt);
            }
        });
        CLIENTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLIENTESActionPerformed(evt);
            }
        });
        jPanel1.add(CLIENTES);
        CLIENTES.setBounds(120, 40, 150, 25);

        VEHICULOS.setLabel("Vehiculos");
        VEHICULOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VEHICULOSMouseClicked(evt);
            }
        });
        VEHICULOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEHICULOSActionPerformed(evt);
            }
        });
        jPanel1.add(VEHICULOS);
        VEHICULOS.setBounds(120, 90, 150, 25);

        ALQUILERES.setText("Alquileres");
        ALQUILERES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ALQUILERESMouseClicked(evt);
            }
        });
        ALQUILERES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALQUILERESActionPerformed(evt);
            }
        });
        jPanel1.add(ALQUILERES);
        ALQUILERES.setBounds(120, 140, 150, 25);

        jLabel1.setText("Territoy Car Rent");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 420, 82, 15);

        DEVOLUTION.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DEVOLUTION.setText("Devolución");
        DEVOLUTION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEVOLUTIONActionPerformed(evt);
            }
        });
        jPanel1.add(DEVOLUTION);
        DEVOLUTION.setBounds(120, 330, 150, 50);

        ATTEND.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ATTEND.setText("Atender Alquiler");
        ATTEND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ATTENDMouseClicked(evt);
            }
        });
        ATTEND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATTENDActionPerformed(evt);
            }
        });
        jPanel1.add(ATTEND);
        ATTEND.setBounds(120, 260, 150, 50);

        NUMBERS.setText("Estadisticas");
        NUMBERS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUMBERSMouseClicked(evt);
            }
        });
        NUMBERS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUMBERSActionPerformed(evt);
            }
        });
        jPanel1.add(NUMBERS);
        NUMBERS.setBounds(120, 190, 150, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CLIENTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLIENTESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLIENTESActionPerformed

    private void VEHICULOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VEHICULOSMouseClicked
        MenuVehiculos ventana = new MenuVehiculos();
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_VEHICULOSMouseClicked

    private void VEHICULOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEHICULOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VEHICULOSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void CLIENTESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLIENTESMouseClicked
        MenuClientes ventana = new MenuClientes();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CLIENTESMouseClicked

    private void ALQUILERESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALQUILERESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALQUILERESActionPerformed

    private void ALQUILERESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALQUILERESMouseClicked
        MenuAlquileres ventana = new MenuAlquileres();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ALQUILERESMouseClicked

    private void DEVOLUTIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEVOLUTIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DEVOLUTIONActionPerformed

    private void ATTENDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATTENDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATTENDActionPerformed

    private void NUMBERSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUMBERSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NUMBERSMouseClicked

    private void NUMBERSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUMBERSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUMBERSActionPerformed

    private void ATTENDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ATTENDMouseClicked
        General.Alquileres_P.atender();
    }//GEN-LAST:event_ATTENDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALQUILERES;
    private javax.swing.JButton ATTEND;
    private javax.swing.JButton CLIENTES;
    private javax.swing.JButton DEVOLUTION;
    private javax.swing.JButton NUMBERS;
    private javax.swing.JButton VEHICULOS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
