/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Clases.*;
/**
 *
 * @author Fabián
 */
public class RegistroVehiculos extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarVehiculo
     */
    public RegistroVehiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTPLACA = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        TXTMONEY = new javax.swing.JTextArea();
        COMBOC = new javax.swing.JComboBox<>();
        COMBOFUEL = new javax.swing.JComboBox<>();
        COMBOMOUNT = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        TXTEXTRA = new javax.swing.JTextArea();
        COMBOSTATUS = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        COMBOCOLOR = new javax.swing.JComboBox<>();
        COMBOBRANCH = new javax.swing.JComboBox<>();
        COMBOMODEL = new javax.swing.JComboBox<>();
        REGISTER = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        EXIT = new javax.swing.JButton();
        COMBOYEAR = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        WARNING = new javax.swing.JLabel();

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Número de placa:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 30, 99, 16);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Marca del vehículo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 60, 109, 16);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Modelo del vehículo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 100, 114, 16);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Año del vehículo:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 130, 95, 16);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Color del vehículo:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 160, 103, 16);

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CC");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 200, 16, 16);

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tipo de combustible:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 230, 117, 16);

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Capacidad de pasajeros:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 270, 140, 16);

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Precio de alquiler por día: $");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 310, 154, 16);

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Información extra:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 350, 104, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Registro de Vehículos");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(120, 0, 210, 30);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TXTPLACA.setBackground(new java.awt.Color(255, 255, 255));
        TXTPLACA.setColumns(20);
        TXTPLACA.setForeground(new java.awt.Color(0, 0, 0));
        TXTPLACA.setRows(5);
        TXTPLACA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(TXTPLACA);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(190, 30, 130, 20);

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TXTMONEY.setBackground(new java.awt.Color(255, 255, 255));
        TXTMONEY.setColumns(20);
        TXTMONEY.setForeground(new java.awt.Color(0, 0, 0));
        TXTMONEY.setRows(5);
        TXTMONEY.setText("0");
        TXTMONEY.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane7.setViewportView(TXTMONEY);

        jPanel1.add(jScrollPane7);
        jScrollPane7.setBounds(190, 310, 110, 20);

        COMBOC.setBackground(new java.awt.Color(255, 255, 255));
        COMBOC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        COMBOC.setForeground(new java.awt.Color(0, 0, 0));
        COMBOC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1500", "2000", "2500", "3000", "4000" }));
        COMBOC.setBorder(new javax.swing.border.MatteBorder(null));
        COMBOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBOCActionPerformed(evt);
            }
        });
        jPanel1.add(COMBOC);
        COMBOC.setBounds(190, 190, 130, 27);

        COMBOFUEL.setBackground(new java.awt.Color(255, 255, 255));
        COMBOFUEL.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        COMBOFUEL.setForeground(new java.awt.Color(0, 0, 0));
        COMBOFUEL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disel", "Gasolina", " " }));
        COMBOFUEL.setBorder(new javax.swing.border.MatteBorder(null));
        COMBOFUEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBOFUELActionPerformed(evt);
            }
        });
        jPanel1.add(COMBOFUEL);
        COMBOFUEL.setBounds(190, 230, 120, 27);

        COMBOMOUNT.setBackground(new java.awt.Color(255, 255, 255));
        COMBOMOUNT.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        COMBOMOUNT.setForeground(new java.awt.Color(0, 0, 0));
        COMBOMOUNT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "7", "8" }));
        COMBOMOUNT.setBorder(new javax.swing.border.MatteBorder(null));
        COMBOMOUNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBOMOUNTActionPerformed(evt);
            }
        });
        jPanel1.add(COMBOMOUNT);
        COMBOMOUNT.setBounds(190, 270, 110, 27);

        jScrollPane9.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TXTEXTRA.setBackground(new java.awt.Color(255, 255, 255));
        TXTEXTRA.setColumns(20);
        TXTEXTRA.setForeground(new java.awt.Color(0, 0, 0));
        TXTEXTRA.setRows(5);
        TXTEXTRA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane9.setViewportView(TXTEXTRA);

        jPanel1.add(jScrollPane9);
        jScrollPane9.setBounds(180, 340, 170, 30);

        COMBOSTATUS.setBackground(new java.awt.Color(255, 255, 255));
        COMBOSTATUS.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        COMBOSTATUS.setForeground(new java.awt.Color(0, 0, 0));
        COMBOSTATUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISPONIBLE", "ALQUILADO", "REPARACIÓN", "OUT" }));
        COMBOSTATUS.setBorder(new javax.swing.border.MatteBorder(null));
        COMBOSTATUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBOSTATUSActionPerformed(evt);
            }
        });
        jPanel1.add(COMBOSTATUS);
        COMBOSTATUS.setBounds(150, 390, 130, 27);

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Estado del vehículo");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 390, 120, 16);

        COMBOCOLOR.setBackground(new java.awt.Color(255, 255, 255));
        COMBOCOLOR.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        COMBOCOLOR.setForeground(new java.awt.Color(0, 0, 0));
        COMBOCOLOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROJO", "AZUL", "AMARILLO", "VERDE", "NARANJA", "MORADO", "BLANCO", "NEGRO" }));
        COMBOCOLOR.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(COMBOCOLOR);
        COMBOCOLOR.setBounds(190, 160, 130, 22);

        COMBOBRANCH.setBackground(new java.awt.Color(255, 255, 255));
        COMBOBRANCH.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        COMBOBRANCH.setForeground(new java.awt.Color(0, 0, 0));
        COMBOBRANCH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Nissan", "Honda", "Ford", "Hyndai", "Mitsubishi", "BMW", "Mazda" }));
        COMBOBRANCH.setBorder(new javax.swing.border.MatteBorder(null));
        COMBOBRANCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBOBRANCHActionPerformed(evt);
            }
        });
        jPanel1.add(COMBOBRANCH);
        COMBOBRANCH.setBounds(190, 60, 130, 27);

        COMBOMODEL.setBackground(new java.awt.Color(255, 255, 255));
        COMBOMODEL.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        COMBOMODEL.setForeground(new java.awt.Color(0, 0, 0));
        COMBOMODEL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automóvil", "Pick up", "SUV", "4x4 Off-Road", " " }));
        COMBOMODEL.setBorder(new javax.swing.border.MatteBorder(null));
        COMBOMODEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBOMODELActionPerformed(evt);
            }
        });
        jPanel1.add(COMBOMODEL);
        COMBOMODEL.setBounds(190, 100, 130, 22);

        REGISTER.setText("Registrar Vehículo");
        REGISTER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REGISTERMouseClicked(evt);
            }
        });
        jPanel1.add(REGISTER);
        REGISTER.setBounds(150, 440, 140, 30);

        jLabel13.setText("Territoy Car Rent");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 470, 82, 15);

        EXIT.setText("Atrás");
        EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITMouseClicked(evt);
            }
        });
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT);
        EXIT.setBounds(390, 460, 61, 20);

        COMBOYEAR.setBackground(new java.awt.Color(255, 255, 255));
        COMBOYEAR.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        COMBOYEAR.setForeground(new java.awt.Color(0, 0, 0));
        COMBOYEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", " " }));
        COMBOYEAR.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(COMBOYEAR);
        COMBOYEAR.setBounds(190, 130, 130, 22);

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Cilindraje del vehículo:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 190, 126, 16);

        WARNING.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        WARNING.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(WARNING);
        WARNING.setBounds(320, 410, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COMBOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOCActionPerformed

    private void COMBOBRANCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOBRANCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOBRANCHActionPerformed

    private void COMBOMOUNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOMOUNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOMOUNTActionPerformed

    private void COMBOFUELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOFUELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOFUELActionPerformed

    private void COMBOMODELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOMODELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOMODELActionPerformed

    private void COMBOSTATUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOSTATUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOSTATUSActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    private void REGISTERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGISTERMouseClicked
    String placa=TXTPLACA.getText(); String marca=COMBOBRANCH.getSelectedItem().toString(); 
    String modelo=COMBOMODEL.getSelectedItem().toString(); int año=Integer.valueOf(COMBOYEAR.getSelectedItem().toString()); 
    String color=COMBOCOLOR.getSelectedItem().toString(); int cilindrada=Integer.valueOf(COMBOC.getSelectedItem().toString());
    String combustible=COMBOFUEL.getSelectedItem().toString();  int capacidad=Integer.valueOf(COMBOMOUNT.getSelectedItem().toString()); 
    double precio=Double.parseDouble(TXTMONEY.getText()); String extras=TXTEXTRA.getText(); String status=COMBOSTATUS.getSelectedItem().toString();
    
    //Validaciones
    if(placa.length()>=6 && precio>=0){
        Vehiculo Carro = new Vehiculo(placa,marca,modelo,año,color,cilindrada,combustible,capacidad,precio,extras);
    General.Vehiculos_Registrados.insertar(Carro);
    MenuVehiculos menu = new MenuVehiculos();
        menu.setVisible(true);
        this.setVisible(false);
    }
    else{
        WARNING.setText("Formato de datos no validos!");
    }
    
    
    
    //Fin de validaciones
    
    
    
    
   
    
    
    
    }//GEN-LAST:event_REGISTERMouseClicked

    private void EXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITMouseClicked
        MenuVehiculos menu = new MenuVehiculos();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EXITMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> COMBOBRANCH;
    private javax.swing.JComboBox<String> COMBOC;
    private javax.swing.JComboBox<String> COMBOCOLOR;
    private javax.swing.JComboBox<String> COMBOFUEL;
    private javax.swing.JComboBox<String> COMBOMODEL;
    private javax.swing.JComboBox<String> COMBOMOUNT;
    private javax.swing.JComboBox<String> COMBOSTATUS;
    private javax.swing.JComboBox<String> COMBOYEAR;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton REGISTER;
    private javax.swing.JTextArea TXTEXTRA;
    private javax.swing.JTextArea TXTMONEY;
    private javax.swing.JTextArea TXTPLACA;
    private javax.swing.JLabel WARNING;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
